
import java.awt.CardLayout;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Alejandro
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        DefaultTableModel tm = (DefaultTableModel) listaContactos.getModel();
        tm.setNumRows(7);
        for (int i = 0; i < 7; i++) {
            tm.addRow(new Object[]{""});
        }
        tm.setValueAt("Juan", 0, 0);
        tm.setValueAt("Jorge", 1, 0);
        tm.setValueAt("José", 2, 0);
        listaContactos.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        pantallaPrincipal = new javax.swing.JPanel();
        añadir = new javax.swing.JButton();
        import_export = new javax.swing.JButton();
        borrarTodo = new javax.swing.JButton();
        consultarContacto = new javax.swing.JButton();
        panelListaContactos = new javax.swing.JScrollPane();
        listaContactos = new javax.swing.JTable();
        barraBusqueda = new javax.swing.JTextField();
        iconoBuscar = new javax.swing.JLabel();
        pantallaEliminarTodos = new javax.swing.JPanel();
        simbAdvertencia = new javax.swing.JLabel();
        panelTextoAdv = new javax.swing.JScrollPane();
        textoAdvert = new javax.swing.JTextArea();
        borrarTodos = new javax.swing.JButton();
        atras1 = new javax.swing.JButton();
        panelConsultarContacto = new javax.swing.JPanel();
        etiqNombre = new javax.swing.JLabel();
        nomContacto = new javax.swing.JLabel();
        etiqListaTel = new javax.swing.JLabel();
        panelListaTel = new javax.swing.JScrollPane();
        listaTel = new javax.swing.JList();
        elimContacto = new javax.swing.JButton();
        actualizarContacto = new javax.swing.JButton();
        atras2 = new javax.swing.JButton();
        panelNuevoContacto = new javax.swing.JPanel();
        etiqNombre1 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        etiqTelefono = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        intrContacto = new javax.swing.JButton();
        atras3 = new javax.swing.JButton();
        pantallaModificar = new javax.swing.JPanel();
        modifNombre = new javax.swing.JButton();
        modifTel = new javax.swing.JButton();
        elimTel = new javax.swing.JButton();
        añadirTel = new javax.swing.JButton();
        etiqModificarContacto = new javax.swing.JLabel();
        atras4 = new javax.swing.JButton();
        pantallaModifNombre = new javax.swing.JPanel();
        etiqModificarNombre = new javax.swing.JLabel();
        etiqInstNom1 = new javax.swing.JLabel();
        etiqInstNom2 = new javax.swing.JLabel();
        campoModifNombre = new javax.swing.JTextField();
        confirmModifNom = new javax.swing.JButton();
        atras5 = new javax.swing.JButton();
        pantallaAñadirTel = new javax.swing.JPanel();
        etiqAñadirTel = new javax.swing.JLabel();
        etiqInstTel1 = new javax.swing.JLabel();
        etiqInstTel2 = new javax.swing.JLabel();
        campoAñadirTel = new javax.swing.JTextField();
        confirmAñadirTel = new javax.swing.JButton();
        atras6 = new javax.swing.JButton();
        pantallaModifTel = new javax.swing.JPanel();
        etiqModificarTel = new javax.swing.JLabel();
        campoModifTel = new javax.swing.JTextField();
        confirmModifTel = new javax.swing.JButton();
        atras7 = new javax.swing.JButton();
        panelListaModifTel = new javax.swing.JScrollPane();
        listaModifTel = new javax.swing.JList();
        pantallaElimTel = new javax.swing.JPanel();
        etiqModificarNombre3 = new javax.swing.JLabel();
        confirmModifNom3 = new javax.swing.JButton();
        atras8 = new javax.swing.JButton();
        panelListaModifTel1 = new javax.swing.JScrollPane();
        listaModifTel1 = new javax.swing.JList();
        pantallaEliminarContacto = new javax.swing.JPanel();
        simbAdvertencia1 = new javax.swing.JLabel();
        panelTextoAdv1 = new javax.swing.JScrollPane();
        textoAdvert1 = new javax.swing.JTextArea();
        borrarCont = new javax.swing.JButton();
        atras9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPrincipal.setBackground(new java.awt.Color(194, 0, 0));
        panelPrincipal.setMaximumSize(new java.awt.Dimension(270, 450));
        panelPrincipal.setMinimumSize(new java.awt.Dimension(270, 450));
        panelPrincipal.setPreferredSize(new java.awt.Dimension(270, 450));
        panelPrincipal.setLayout(new java.awt.CardLayout());

        pantallaPrincipal.setBackground(new java.awt.Color(194, 0, 0));
        pantallaPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        añadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492014114_add.png"))); // NOI18N
        añadir.setToolTipText("Añadir contacto");
        añadir.setBorder(null);
        añadir.setContentAreaFilled(false);
        añadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirActionPerformed(evt);
            }
        });
        pantallaPrincipal.add(añadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        import_export.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492015789_ic_import_export_48px.png"))); // NOI18N
        import_export.setToolTipText("Importar/Exportar .csv");
        import_export.setBorder(null);
        import_export.setContentAreaFilled(false);
        pantallaPrincipal.add(import_export, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        borrarTodo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492016036_ic_delete_48px.png"))); // NOI18N
        borrarTodo.setToolTipText("Borrar todos los contactos");
        borrarTodo.setBorder(null);
        borrarTodo.setContentAreaFilled(false);
        borrarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodoActionPerformed(evt);
            }
        });
        pantallaPrincipal.add(borrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        consultarContacto.setText("Acceder a contacto");
        consultarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarContactoActionPerformed(evt);
            }
        });
        pantallaPrincipal.add(consultarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        listaContactos.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        listaContactos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lista de contactos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaContactos.setRowHeight(40);
        listaContactos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        panelListaContactos.setViewportView(listaContactos);

        pantallaPrincipal.add(panelListaContactos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 270, 230));

        barraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraBusquedaActionPerformed(evt);
            }
        });
        pantallaPrincipal.add(barraBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 180, -1));

        iconoBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492100714_search.png"))); // NOI18N
        iconoBuscar.setToolTipText("Buscar contacto: introduce el nombre y pulsa Enter");
        pantallaPrincipal.add(iconoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        panelPrincipal.add(pantallaPrincipal, "pantallaPrincipal");

        pantallaEliminarTodos.setBackground(new java.awt.Color(194, 0, 0));
        pantallaEliminarTodos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simbAdvertencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492101646_warning-outline.png"))); // NOI18N
        pantallaEliminarTodos.add(simbAdvertencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        panelTextoAdv.setBackground(new java.awt.Color(194, 0, 0));
        panelTextoAdv.setBorder(null);
        panelTextoAdv.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelTextoAdv.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textoAdvert.setEditable(false);
        textoAdvert.setBackground(new java.awt.Color(194, 0, 0));
        textoAdvert.setColumns(20);
        textoAdvert.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        textoAdvert.setForeground(new java.awt.Color(1, 0, 0));
        textoAdvert.setRows(5);
        textoAdvert.setText("Se borrarán todos los contactos\n  de la agenda. ¿Está seguro?");
        textoAdvert.setBorder(null);
        panelTextoAdv.setViewportView(textoAdvert);

        pantallaEliminarTodos.add(panelTextoAdv, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        borrarTodos.setText("Borrar todos");
        borrarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarTodosActionPerformed(evt);
            }
        });
        pantallaEliminarTodos.add(borrarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        atras1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras1.setToolTipText("Volver atrás");
        atras1.setBorder(null);
        atras1.setContentAreaFilled(false);
        atras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras1ActionPerformed(evt);
            }
        });
        pantallaEliminarTodos.add(atras1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelPrincipal.add(pantallaEliminarTodos, "pantallaEliminarTodos");

        panelConsultarContacto.setBackground(new java.awt.Color(194, 0, 0));
        panelConsultarContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqNombre.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        etiqNombre.setForeground(new java.awt.Color(1, 0, 0));
        etiqNombre.setText("Nombre:");
        panelConsultarContacto.add(etiqNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        nomContacto.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        nomContacto.setForeground(new java.awt.Color(1, 0, 0));
        nomContacto.setText("Jorge");
        panelConsultarContacto.add(nomContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        etiqListaTel.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        etiqListaTel.setForeground(new java.awt.Color(1, 0, 0));
        etiqListaTel.setText("Lista de teléfonos:");
        panelConsultarContacto.add(etiqListaTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        panelListaTel.setBorder(null);

        listaTel.setBackground(new java.awt.Color(194, 0, 0));
        listaTel.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        listaTel.setForeground(new java.awt.Color(1, 0, 0));
        listaTel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "600890912", "913425600" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaTel.setVisibleRowCount(7);
        panelListaTel.setViewportView(listaTel);

        panelConsultarContacto.add(panelListaTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 270, 140));

        elimContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492016036_ic_delete_48px.png"))); // NOI18N
        elimContacto.setToolTipText("Eliminar contacto");
        elimContacto.setBorder(null);
        elimContacto.setContentAreaFilled(false);
        elimContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimContactoActionPerformed(evt);
            }
        });
        panelConsultarContacto.add(elimContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 40, 40));

        actualizarContacto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102966_refresh.png"))); // NOI18N
        actualizarContacto.setToolTipText("Modificar");
        actualizarContacto.setBorder(null);
        actualizarContacto.setContentAreaFilled(false);
        actualizarContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarContactoActionPerformed(evt);
            }
        });
        panelConsultarContacto.add(actualizarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 40, 40));

        atras2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras2.setToolTipText("Volver atrás");
        atras2.setBorder(null);
        atras2.setContentAreaFilled(false);
        atras2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras2ActionPerformed(evt);
            }
        });
        panelConsultarContacto.add(atras2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelPrincipal.add(panelConsultarContacto, "pantallaConsultar");

        panelNuevoContacto.setBackground(new java.awt.Color(194, 0, 0));
        panelNuevoContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqNombre1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        etiqNombre1.setForeground(new java.awt.Color(1, 0, 0));
        etiqNombre1.setText("Teléfono:");
        panelNuevoContacto.add(etiqNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        campoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefonoActionPerformed(evt);
            }
        });
        panelNuevoContacto.add(campoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, -1));

        etiqTelefono.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        etiqTelefono.setForeground(new java.awt.Color(1, 0, 0));
        etiqTelefono.setText("Nombre:");
        panelNuevoContacto.add(etiqTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        panelNuevoContacto.add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, -1));

        intrContacto.setText("Añadir contacto");
        intrContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intrContactoActionPerformed(evt);
            }
        });
        panelNuevoContacto.add(intrContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        atras3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras3.setToolTipText("Volver atrás");
        atras3.setBorder(null);
        atras3.setContentAreaFilled(false);
        atras3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras3ActionPerformed(evt);
            }
        });
        panelNuevoContacto.add(atras3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelPrincipal.add(panelNuevoContacto, "pantallaNuevo");

        pantallaModificar.setBackground(new java.awt.Color(194, 0, 0));
        pantallaModificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        modifNombre.setText("Modificar nombre");
        modifNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifNombreActionPerformed(evt);
            }
        });
        pantallaModificar.add(modifNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 180, 180, -1));

        modifTel.setText("Modificar teléfono");
        modifTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifTelActionPerformed(evt);
            }
        });
        pantallaModificar.add(modifTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 280, 180, -1));

        elimTel.setText("Eliminar teléfono");
        elimTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimTelActionPerformed(evt);
            }
        });
        pantallaModificar.add(elimTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 330, 180, -1));

        añadirTel.setText("Añadir teléfono");
        añadirTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirTelActionPerformed(evt);
            }
        });
        pantallaModificar.add(añadirTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 230, 180, -1));

        etiqModificarContacto.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        etiqModificarContacto.setForeground(new java.awt.Color(1, 0, 0));
        etiqModificarContacto.setText("Modificar contacto");
        pantallaModificar.add(etiqModificarContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        atras4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras4.setToolTipText("Volver atrás");
        atras4.setBorder(null);
        atras4.setContentAreaFilled(false);
        atras4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras4ActionPerformed(evt);
            }
        });
        pantallaModificar.add(atras4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelPrincipal.add(pantallaModificar, "pantallaModificar");

        pantallaModifNombre.setBackground(new java.awt.Color(194, 0, 0));
        pantallaModifNombre.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqModificarNombre.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        etiqModificarNombre.setForeground(new java.awt.Color(1, 0, 0));
        etiqModificarNombre.setText("Modificar nombre");
        pantallaModifNombre.add(etiqModificarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        etiqInstNom1.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        etiqInstNom1.setForeground(new java.awt.Color(1, 0, 0));
        etiqInstNom1.setText("Introduce el nuevo nombre");
        pantallaModifNombre.add(etiqInstNom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 40));

        etiqInstNom2.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        etiqInstNom2.setForeground(new java.awt.Color(1, 0, 0));
        etiqInstNom2.setText("del contacto");
        pantallaModifNombre.add(etiqInstNom2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        campoModifNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModifNombreActionPerformed(evt);
            }
        });
        pantallaModifNombre.add(campoModifNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        confirmModifNom.setText("Aceptar");
        confirmModifNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmModifNomActionPerformed(evt);
            }
        });
        pantallaModifNombre.add(confirmModifNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        atras5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras5.setToolTipText("Volver atrás");
        atras5.setBorder(null);
        atras5.setContentAreaFilled(false);
        atras5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras5ActionPerformed(evt);
            }
        });
        pantallaModifNombre.add(atras5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelPrincipal.add(pantallaModifNombre, "pantallaModifNombre");

        pantallaAñadirTel.setBackground(new java.awt.Color(194, 0, 0));
        pantallaAñadirTel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqAñadirTel.setFont(new java.awt.Font("Eras Medium ITC", 1, 25)); // NOI18N
        etiqAñadirTel.setForeground(new java.awt.Color(1, 0, 0));
        etiqAñadirTel.setText("Añadir teléfono");
        pantallaAñadirTel.add(etiqAñadirTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        etiqInstTel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        etiqInstTel1.setForeground(new java.awt.Color(1, 0, 0));
        etiqInstTel1.setText("Introduce el nuevo teléfono");
        pantallaAñadirTel.add(etiqInstTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 40));

        etiqInstTel2.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        etiqInstTel2.setForeground(new java.awt.Color(1, 0, 0));
        etiqInstTel2.setText("del contacto");
        pantallaAñadirTel.add(etiqInstTel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        campoAñadirTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAñadirTelActionPerformed(evt);
            }
        });
        pantallaAñadirTel.add(campoAñadirTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 190, -1));

        confirmAñadirTel.setText("Aceptar");
        confirmAñadirTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmAñadirTelActionPerformed(evt);
            }
        });
        pantallaAñadirTel.add(confirmAñadirTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        atras6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras6.setToolTipText("Volver atrás");
        atras6.setBorder(null);
        atras6.setContentAreaFilled(false);
        atras6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras6ActionPerformed(evt);
            }
        });
        pantallaAñadirTel.add(atras6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelPrincipal.add(pantallaAñadirTel, "pantallaAñadirTel");

        pantallaModifTel.setBackground(new java.awt.Color(194, 0, 0));
        pantallaModifTel.setForeground(new java.awt.Color(1, 0, 0));
        pantallaModifTel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqModificarTel.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        etiqModificarTel.setForeground(new java.awt.Color(1, 0, 0));
        etiqModificarTel.setText("Modificar teléfono");
        pantallaModifTel.add(etiqModificarTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        campoModifTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoModifTelActionPerformed(evt);
            }
        });
        pantallaModifTel.add(campoModifTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 190, -1));

        confirmModifTel.setText("Modificar");
        confirmModifTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmModifTelActionPerformed(evt);
            }
        });
        pantallaModifTel.add(confirmModifTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        atras7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras7.setToolTipText("Volver atrás");
        atras7.setBorder(null);
        atras7.setContentAreaFilled(false);
        atras7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras7ActionPerformed(evt);
            }
        });
        pantallaModifTel.add(atras7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelListaModifTel.setBorder(null);

        listaModifTel.setBackground(new java.awt.Color(194, 0, 0));
        listaModifTel.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        listaModifTel.setForeground(new java.awt.Color(1, 0, 0));
        listaModifTel.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "600890912", "913425600" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaModifTel.setVisibleRowCount(5);
        panelListaModifTel.setViewportView(listaModifTel);

        pantallaModifTel.add(panelListaModifTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 130, 120));

        panelPrincipal.add(pantallaModifTel, "pantallaModifTel");

        pantallaElimTel.setBackground(new java.awt.Color(194, 0, 0));
        pantallaElimTel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqModificarNombre3.setFont(new java.awt.Font("Eras Medium ITC", 1, 24)); // NOI18N
        etiqModificarNombre3.setForeground(new java.awt.Color(1, 0, 0));
        etiqModificarNombre3.setText("Eliminar teléfono");
        pantallaElimTel.add(etiqModificarNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        confirmModifNom3.setText("Eliminar");
        confirmModifNom3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmModifNom3ActionPerformed(evt);
            }
        });
        pantallaElimTel.add(confirmModifNom3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 90, -1));

        atras8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras8.setToolTipText("Volver atrás");
        atras8.setBorder(null);
        atras8.setContentAreaFilled(false);
        atras8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras8ActionPerformed(evt);
            }
        });
        pantallaElimTel.add(atras8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelListaModifTel1.setBorder(null);

        listaModifTel1.setBackground(new java.awt.Color(194, 0, 0));
        listaModifTel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        listaModifTel1.setForeground(new java.awt.Color(1, 0, 0));
        listaModifTel1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "600890912", "913425600" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaModifTel1.setSelectionBackground(new java.awt.Color(0, 0, 0));
        panelListaModifTel1.setViewportView(listaModifTel1);

        pantallaElimTel.add(panelListaModifTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 130, 170));

        panelPrincipal.add(pantallaElimTel, "pantallaElimTel");

        pantallaEliminarContacto.setBackground(new java.awt.Color(194, 0, 0));
        pantallaEliminarContacto.setPreferredSize(new java.awt.Dimension(270, 450));
        pantallaEliminarContacto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simbAdvertencia1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492101646_warning-outline.png"))); // NOI18N
        pantallaEliminarContacto.add(simbAdvertencia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        panelTextoAdv1.setBackground(new java.awt.Color(194, 0, 0));
        panelTextoAdv1.setBorder(null);
        panelTextoAdv1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        panelTextoAdv1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textoAdvert1.setEditable(false);
        textoAdvert1.setBackground(new java.awt.Color(194, 0, 0));
        textoAdvert1.setColumns(20);
        textoAdvert1.setFont(new java.awt.Font("Eras Medium ITC", 1, 16)); // NOI18N
        textoAdvert1.setForeground(new java.awt.Color(1, 0, 0));
        textoAdvert1.setRows(5);
        textoAdvert1.setText("       Se borrará el contacto de\n       la agenda. ¿Está seguro?");
        textoAdvert1.setBorder(null);
        panelTextoAdv1.setViewportView(textoAdvert1);

        pantallaEliminarContacto.add(panelTextoAdv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, -1, -1));

        borrarCont.setText("Borrar contacto");
        borrarCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarContActionPerformed(evt);
            }
        });
        pantallaEliminarContacto.add(borrarCont, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        atras9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/1492102310_icon-ios7-arrow-back.png"))); // NOI18N
        atras9.setToolTipText("Volver atrás");
        atras9.setBorder(null);
        atras9.setContentAreaFilled(false);
        atras9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atras9ActionPerformed(evt);
            }
        });
        pantallaEliminarContacto.add(atras9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        panelPrincipal.add(pantallaEliminarContacto, "pantallaEliminarContacto");

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void añadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaNuevo");
    }//GEN-LAST:event_añadirActionPerformed

    private void borrarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodoActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaEliminarTodos");
    }//GEN-LAST:event_borrarTodoActionPerformed

    private void barraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBusquedaActionPerformed

        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) listaContactos.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(barraBusqueda.getText()));

        listaContactos.setRowSorter(sorter);

    }//GEN-LAST:event_barraBusquedaActionPerformed

    private void borrarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarTodosActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaPrincipal");
    }//GEN-LAST:event_borrarTodosActionPerformed

    private void actualizarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarContactoActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaModificar");
    }//GEN-LAST:event_actualizarContactoActionPerformed

    private void campoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefonoActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void intrContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intrContactoActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaPrincipal");
    }//GEN-LAST:event_intrContactoActionPerformed

    private void consultarContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarContactoActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaConsultar");
    }//GEN-LAST:event_consultarContactoActionPerformed

    private void atras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras1ActionPerformed
        barraBusqueda.setText("");
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaPrincipal");
    }//GEN-LAST:event_atras1ActionPerformed

    private void atras2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras2ActionPerformed
        barraBusqueda.setText("");
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaPrincipal");
    }//GEN-LAST:event_atras2ActionPerformed

    private void atras3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras3ActionPerformed
        barraBusqueda.setText("");
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaPrincipal");
    }//GEN-LAST:event_atras3ActionPerformed

    private void atras4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras4ActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaConsultar");
    }//GEN-LAST:event_atras4ActionPerformed

    private void campoModifNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModifNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModifNombreActionPerformed

    private void atras5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras5ActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaModificar");
    }//GEN-LAST:event_atras5ActionPerformed

    private void campoAñadirTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAñadirTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAñadirTelActionPerformed

    private void atras6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras6ActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaModificar");
    }//GEN-LAST:event_atras6ActionPerformed

    private void campoModifTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoModifTelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoModifTelActionPerformed

    private void atras7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras7ActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaModificar");
    }//GEN-LAST:event_atras7ActionPerformed

    private void atras8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras8ActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaModificar");
    }//GEN-LAST:event_atras8ActionPerformed

    private void confirmModifNom3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmModifNom3ActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaConsultar");
    }//GEN-LAST:event_confirmModifNom3ActionPerformed

    private void borrarContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarContActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaPrincipal");
    }//GEN-LAST:event_borrarContActionPerformed

    private void atras9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atras9ActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaConsultar");
    }//GEN-LAST:event_atras9ActionPerformed

    private void elimContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimContactoActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaEliminarContacto");
    }//GEN-LAST:event_elimContactoActionPerformed

    private void modifNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifNombreActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaModifNombre");
    }//GEN-LAST:event_modifNombreActionPerformed

    private void añadirTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirTelActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaAñadirTel");
    }//GEN-LAST:event_añadirTelActionPerformed

    private void modifTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifTelActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaModifTel");
    }//GEN-LAST:event_modifTelActionPerformed

    private void elimTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimTelActionPerformed
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaElimTel");
    }//GEN-LAST:event_elimTelActionPerformed

    private void confirmModifNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmModifNomActionPerformed
        campoModifNombre.setText("");
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaConsultar");
    }//GEN-LAST:event_confirmModifNomActionPerformed

    private void confirmAñadirTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmAñadirTelActionPerformed
        campoAñadirTel.setText("");
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaConsultar");
    }//GEN-LAST:event_confirmAñadirTelActionPerformed

    private void confirmModifTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmModifTelActionPerformed
        campoModifTel.setText("");
        CardLayout card = (CardLayout) panelPrincipal.getLayout();
        card.show(panelPrincipal, "pantallaConsultar");
    }//GEN-LAST:event_confirmModifTelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarContacto;
    private javax.swing.JButton atras1;
    private javax.swing.JButton atras2;
    private javax.swing.JButton atras3;
    private javax.swing.JButton atras4;
    private javax.swing.JButton atras5;
    private javax.swing.JButton atras6;
    private javax.swing.JButton atras7;
    private javax.swing.JButton atras8;
    private javax.swing.JButton atras9;
    private javax.swing.JButton añadir;
    private javax.swing.JButton añadirTel;
    private javax.swing.JTextField barraBusqueda;
    private javax.swing.JButton borrarCont;
    private javax.swing.JButton borrarTodo;
    private javax.swing.JButton borrarTodos;
    private javax.swing.JTextField campoAñadirTel;
    private javax.swing.JTextField campoModifNombre;
    private javax.swing.JTextField campoModifTel;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JButton confirmAñadirTel;
    private javax.swing.JButton confirmModifNom;
    private javax.swing.JButton confirmModifNom3;
    private javax.swing.JButton confirmModifTel;
    private javax.swing.JButton consultarContacto;
    private javax.swing.JButton elimContacto;
    private javax.swing.JButton elimTel;
    private javax.swing.JLabel etiqAñadirTel;
    private javax.swing.JLabel etiqInstNom1;
    private javax.swing.JLabel etiqInstNom2;
    private javax.swing.JLabel etiqInstTel1;
    private javax.swing.JLabel etiqInstTel2;
    private javax.swing.JLabel etiqListaTel;
    private javax.swing.JLabel etiqModificarContacto;
    private javax.swing.JLabel etiqModificarNombre;
    private javax.swing.JLabel etiqModificarNombre3;
    private javax.swing.JLabel etiqModificarTel;
    private javax.swing.JLabel etiqNombre;
    private javax.swing.JLabel etiqNombre1;
    private javax.swing.JLabel etiqTelefono;
    private javax.swing.JLabel iconoBuscar;
    private javax.swing.JButton import_export;
    private javax.swing.JButton intrContacto;
    private javax.swing.JTable listaContactos;
    private javax.swing.JList listaModifTel;
    private javax.swing.JList listaModifTel1;
    private javax.swing.JList listaTel;
    private javax.swing.JButton modifNombre;
    private javax.swing.JButton modifTel;
    private javax.swing.JLabel nomContacto;
    private javax.swing.JPanel panelConsultarContacto;
    private javax.swing.JScrollPane panelListaContactos;
    private javax.swing.JScrollPane panelListaModifTel;
    private javax.swing.JScrollPane panelListaModifTel1;
    private javax.swing.JScrollPane panelListaTel;
    private javax.swing.JPanel panelNuevoContacto;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JScrollPane panelTextoAdv;
    private javax.swing.JScrollPane panelTextoAdv1;
    private javax.swing.JPanel pantallaAñadirTel;
    private javax.swing.JPanel pantallaElimTel;
    private javax.swing.JPanel pantallaEliminarContacto;
    private javax.swing.JPanel pantallaEliminarTodos;
    private javax.swing.JPanel pantallaModifNombre;
    private javax.swing.JPanel pantallaModifTel;
    private javax.swing.JPanel pantallaModificar;
    private javax.swing.JPanel pantallaPrincipal;
    private javax.swing.JLabel simbAdvertencia;
    private javax.swing.JLabel simbAdvertencia1;
    private javax.swing.JTextArea textoAdvert;
    private javax.swing.JTextArea textoAdvert1;
    // End of variables declaration//GEN-END:variables
}
